# Error Handling

## Catching Errors

아래와 같이 에러가 발생하면 Express에서 에러를 감지한다. 

```javascript
app.get('/', function (req, res) {
  throw new Error('BROKEN') // Express will catch this on its own.
})
```

비동기로 실행되는 미들웨어의 코드는 `next()`함수에 에러를 넣어준다. 

```javascript
app.get('/', function (req, res, next) {
  fs.readFile('/file-does-not-exist', function (err, data) {
    if (err) {
      next(err) // Pass errors to Express.
    } else {
      res.send(data)
    }
  })
})
```